{% set version = "1.0.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-dartr.data
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/dartR.data_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/dartR.data/dartR.data_{{ version }}.tar.gz
  sha256: 37164e65c54a18a80b883d77dba2754284331ae16ffca3041b5cce392dc7369d

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-adegenet >=2.0.0
  run:
    - r-base
    - r-adegenet >=2.0.0

test:
  commands:
    - $R -e "library('dartR.data')"           # [not win]
    - "\"%R%\" -e \"library('dartR.data')\""  # [win]

about:
  home: https://github.com/green-striped-gecko/dartR.data
  license: GPL-3.0-or-later
  summary: Data package for 'dartR'. Provides data sets to run examples in 'dartR'. This was necessary due to the size limit imposed by 'CRAN'. The data in 'dartR.data' is needed to run the examples provided in the 'dartR' functions. All available data sets are either based on actual data (but reduced in size) and/or simulated
    data sets to allow the fast execution of examples and demonstration of the functions.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
